### PR TITLE
Fix #164 Built server-side TS files end up in a wrong folder

### LINKED ISSUE #164: Built server-side TS files end up in a wrong folder
If a part mypart has a .ts controller under `main/resources/site/parts/mypart/mainpart.ts` then build will put produced .js file in `main/resources` instead of `main/resources/site/parts/mypart/`

### PR DESCRIPTION
**Pull request by ComLock**

### CODE REVIEW

**Review by alansemenov — APPROVED** [review]

File: tsup/dict.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+type KeyValuePair<K extends string | number | symbol, V> = [K, V];
```
Comment (tajakobsen) [inline tsup/dict.ts:1]: Could this be:
```suggestion
type KeyValuePair<K extends PropertyKey, V> = [K, V];
```

since `PropertyKey` = `string | number | symbol`

**Review by tajakobsen — APPROVED** [review]
Looks good. Tested on Ubuntu and Windows, and everything appears to be working now.

File: tsup/dict.ts (hunk 1 above)
Comment (ComLock) [reply tsup/dict.ts:1]: I had the dict function from previous webpack js file, and I just lazily used claude to type it for me, without thinking :)
